### ISSUE TITLE
你好，我这个不清楚为啥运行不了，谢谢

### ISSUE THREAD

**Issue by OVER4041** [Ikaros-521/nonebot_plugin_openAI_completions#1]
12-06 20:15:30 [ERROR] nonebot | Failed to import "nonebot_plugin_openAI_completions"
Traceback (most recent call last):
  File "e:\pbot\nb1\bot.py", line 35, in <module>
    nonebot.load_plugin("nonebot_plugin_openAI_completions")
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonebot_plugin_openAI_completions'
![image](https://user-images.githubusercontent.com/91008090/205910404-9ea65ebf-918f-4712-b1ac-25f97107eef1.png)
谢谢大佬，麻烦您了

**Comment by Ikaros-521** [comment]
导入 `nonebot_plugin_openAI_completions`改为`nonebot_plugin_openai_completions`，我文档直接复制的，没注意大小写，试试看

**Comment by Ikaros-521** [comment]
玩chatGPT的话推荐装 https://github.com/A-kirami/nonebot-plugin-chatgpt 这个。

completions这个openAI的接口对话还是比较拉的，有些回复有很怪

**Comment by OVER4041** [comment]
谢谢大佬，现在好了，非常感谢捏

**Comment by Ikaros-521** [comment]
可以的www
